### ISSUE TITLE
Wallet provider - Massa Wallet needed exemples

### ISSUE THREAD

**Issue by SlnPons** [massalabs/massa-sc-examples#141]
**Context**
Enable all builders to achieve what they want with Massa Wallet product.

**How to**
Add clear exemples that people can easily reproduce on their side to: 
- [ ] Connect to Massa Wallet app
- [ ] Retrieve all existing accounts
- [ ] Render Massa Wallet in a pop-up (or equivalent) to enable users to connect and/or create a new account
- [ ] 

**Technical details**
TBD
**QA testing**
TBD

**Comment by gregLibert** [comment]
@Elli610 You will find here more examples to be covered. I think we also should add them to docu-dev.

**Comment by Elli610** [comment]
> @Elli610 You will find here more examples to be covered. I think we also should add them to docu-dev.

Yes !
I am currently working on a way to simplify the initialization of the provider.
Once I have your feedback on it I will make a clear doc and examples for that

**Comment by Elli610** [comment]
Hi @SlnPons !

Here is an updated version for the sum example frontend https://github.com/massalabs/massa-sc-examples/pull/149. Is it what you expected ?

**Comment by SlnPons** [comment]
> Hi @SlnPons !
> 
> Here is an updated version for the sum example frontend #149. Is it what you expected ?

@Elli610 what do you mean by `sum example frondend` please?

**Comment by Elli610** [comment]
we updated the frontend to match what you asked for. Is this what you expected ?
here: https://github.com/massalabs/massa-sc-examples/pull/149.
