### ISSUE TITLE
Update front end examples

### ISSUE THREAD

**Issue by julienbrs** [massalabs/massa-sc-examples#76]
**Context**
Contracts examples have been updated but not the frontend. Need to check which ones are working and which ones should be updated. 

The only way to connect a wallet to the front end should be Massa Station (Thyra).
The [Wallet provider](https://github.com/massalabs/wallet-provider) should be used to connect thyra to the front end

- [ ] Update the CONTRIBUTING file to explain how to deal with the standard front end (what should be personalized, etc)
- [x] #77
- [ ] Update async-calls front
- [x] #106
- [ ] Update tictactoe front
- [x] #80
- [x] #79
- [x] #81
